# Generated by Django 5.0.6 on 2024-07-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bciitapp', '0002_alter_myregister_fname'),
    ]

    operations = [
        migrations.AddField(
            model_name='myregister',
            name='course',
            field=models.CharField(default='BCA', max_length=50),
        ),
    ]
