# Generated by Django 5.0.6 on 2024-07-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bciitapp', '0004_alter_myregister_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myregister',
            name='course',
            field=models.CharField(default='bca', max_length=50),
        ),
    ]
