# Generated by Django 5.0.6 on 2024-07-25 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bciitapp', '0008_myupload_remove_image_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='image',
            new_name='myimage',
        ),
        migrations.RenameField(
            model_name='myimage',
            old_name='fname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='myimage',
            old_name='lname',
            new_name='lastname',
        ),
    ]
