# Generated by Django 5.0.6 on 2024-07-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bciitapp', '0009_rename_image_myimage_rename_fname_myimage_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myregister',
            name='file',
            field=models.FileField(default='not available', upload_to=''),
        ),
    ]
