# Generated by Django 5.0.6 on 2024-07-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bciitapp', '0010_myregister_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myimage',
        ),
        migrations.DeleteModel(
            name='myupload',
        ),
        migrations.AddField(
            model_name='myregister',
            name='image',
            field=models.ImageField(default='not available', upload_to=''),
        ),
    ]
