# Generated by Django 5.0.6 on 2024-07-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bciitapp', '0011_delete_myimage_delete_myupload_myregister_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myregister',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
