# Generated by Django 5.0.6 on 2024-07-27 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bciitapp', '0012_alter_myregister_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myregister',
            name='image',
        ),
    ]
